env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-simple-import-sort'
rules:
  "@typescript-eslint/no-non-null-assertion":
    - 0
  "@typescript-eslint/no-unused-vars":
    - error
  "@typescript-eslint/no-var-requires":
    - 0
  'simple-import-sort/imports':
    - warn
  # func-style:
  #   - warn
  #   - expression